export const PROFILE_AVATAR_DIMENSIONS_TYPES = {
  EXTRA_SMALL: "extra-small",
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
};

export const PROFILE_AVATAR_BADGE_DIMENSIONS_TYPES = {
  EXTRA_SMALL: "extra-small",
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
};

export const COVER_IMAGE_DIMENSIONS_TYPES = {
  EXTRA_SMALL: "extra-small",
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
};

export const PROFILE_BIO_CARD_DIMENSIONS_TYPES = {
  PORTRAIT: "portrait",
  LANDSCAPE: "landscape",
};

export const PROFILE_BIO_CARD_VIEW_TYPES = {
  BRIEF: "brief",
  DETAIL: "detail",
};

export const PROFILE_AVATAR_DIMENSIONS = {
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.EXTRA_SMALL]: { width: 40, height: 40 },
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.SMALL]: { width: 50, height: 50 },
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.MEDIUM]: { width: 70, height: 70 },
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.LARGE]: { width: 120, height: 120 },
};

export const PROFILE_AVATAR_CARD_PADDING = {
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.EXTRA_SMALL]: 2,
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.SMALL]: 2,
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.MEDIUM]: 2,
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.LARGE]: 2,
};

export const PROFILE_AVATAR_BADGE_DIMENSIONS = {
  [PROFILE_AVATAR_BADGE_DIMENSIONS_TYPES?.EXTRA_SMALL]: {
    width: 18,
    height: 18,
  },
  [PROFILE_AVATAR_BADGE_DIMENSIONS_TYPES?.SMALL]: { width: 20, height: 20 },
  [PROFILE_AVATAR_BADGE_DIMENSIONS_TYPES?.MEDIUM]: { width: 24, height: 24 },
  [PROFILE_AVATAR_BADGE_DIMENSIONS_TYPES?.LARGE]: { width: 24, height: 24 },
};

export const COVER_IMAGE_DIMENSIONS = {
  [COVER_IMAGE_DIMENSIONS_TYPES?.SMALL]: { height: 60 },
  [COVER_IMAGE_DIMENSIONS_TYPES?.MEDIUM]: { height: 100 },
  [COVER_IMAGE_DIMENSIONS_TYPES?.LARGE]: { height: 200 },
};

export const PROFILE_STATUS_BADGE_MARGIN = {
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.EXTRA_SMALL]: 1.2,
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.SMALL]: 1.2,
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.MEDIUM]: 1.7,
  [PROFILE_AVATAR_DIMENSIONS_TYPES?.LARGE]: 2.5,
};
