export const ROUTES = {
  HOME: "/",
  NEWS_FEED: "/",
  OVERVIEW: "/overview",
  GROUPS: "/groups",
  MEMBERS: "/members",
  BADGES: "/badges",
  QUEST: "/quest",
  STREAMS: "/streams",
  EVENTS: "/events",
  FORUMS: "/forums",
  MARKETPLACE: "/marketplace",
  SIGNIN: "/auth/signin",
  SIGNUP: "/auth/signup",
  FORGOT_PASSWORD: "/auth/forgot-password",
  CONTACT_US: "/contact-us",
  CAREER: "/career",
  FAQ: "/faqs",
};
